### ISSUE TITLE
How do I load the other datasets?

### ISSUE THREAD

**Issue by amalic** [mo-ld/mold-dock#2]
Here's what I did
```
git clone https://github.com/mo-ld/mold-dock.git
cd mold-dock

curl -L http://mo-ld.org/download/yeastmold-vt.tar.gz | tar xvz
mv yeastmold-vt mold-virtuoso
curl -L http://mo-ld.org/download/zebrafishmold-vt.tar.gz | tar xvz
mv zebrafishmold-vt mold-virtuoso
curl -L http://mo-ld.org/download/flymold-vt.tar.gz | tar xvz
mv flymold-vt mold-virtuoso
curl -L http://mo-ld.org/download/ratmold-vt.tar.gz | tar xvz
mv ratmold-vt mold-virtuoso
curl -L http://mo-ld.org/download/mousemold-vt.tar.gz | tar xvz
mv mousemold-vt mold-virtuoso
curl -L http://mo-ld.org/download/humanmold-vt.tar.gz | tar xvz
mv humanmold-vt mold-virtuoso

docker-compose -f docker-compose.hub.yml -p mold up -d
```

After his I have following files in my mold-virtuoso directory
```
mold-virtuoso$ ls
flymold-vt  humanmold-vt  mousemold-vt  ratmold-vt  virtuoso.db  virtuoso.lck  virtuoso.log  virtuoso.pxa  virtuoso.tdb  virtuoso.trx  yeastmold-vt  zebrafishmold-vt
```

I am still only able to query Yeastmold data.

**Comment by justinccdev** [comment]
@amalic Were you able to download these tars?  I tried just now and get 404s

**Comment by zorino** [comment]
I also get 404s when trying to download the tar files.
Unfortunately I am no longer in charge of the production server.
@micheldumontier can you help us with that one ?

**Comment by amalic** [comment]
@zorino @justinccdev 
We have changed the DNS entry. It is now pointing to the new server. I have not added the downloads yet since they have not been part of mold-dock. 

you can download the files via the servers old ip-address
```
git clone https://github.com/mo-ld/mold-dock.git
cd mold-dock

curl -L http://171.67.213.207/download/yeastmold-vt.tar.gz | tar xvz
mv yeastmold-vt mold-virtuoso
curl -L http://171.67.213.207/download/zebrafishmold-vt.tar.gz | tar xvz
mv zebrafishmold-vt mold-virtuoso
curl -L http://171.67.213.207/download/flymold-vt.tar.gz | tar xvz
mv flymold-vt mold-virtuoso
curl -L http://171.67.213.207/download/ratmold-vt.tar.gz | tar xvz
mv ratmold-vt mold-virtuoso
curl -L http://171.67.213.207/download/mousemold-vt.tar.gz | tar xvz
mv mousemold-vt mold-virtuoso
curl -L http://171.67.213.207/download/humanmold-vt.tar.gz | tar xvz
mv humanmold-vt mold-virtuoso

docker-compose -f docker-compose.hub.yml -p mold up -d
```

**Comment by amalic** [comment]
Downloads also work now on the new server. Those http links from the first post in this thread redirect properly to https.

**Comment by amalic** [comment]
Hi Zorino, I still have the issue that only the yeastmold dataset is loaded in the application. How do I load the other datasets?

**Comment by zorino** [comment]
The virtuoso dump were separate builds of each model organisms database.
If you want to have all of them under one database you'll need to upload the raw data into one virtuoso instance.
We had some backup of the tsv raw files on the old server.
Otherwise you'll need to extract it from each virtuoso instance.

**Comment by amalic** [comment]
any idea how we could automate this? 
we have the downloads right? it would be cool if we could do this inside a container.
